# expect: UNDECLARED_READ
world("shared draw", closed=True)
horizon(2, source="elicited")
depth(2, source="elicited")
space({"side": ["x", "y"], "lambda": ["p", "m"]})
prior({("x", "p"): 3/8, ("x", "m"): 1/8, ("y", "p"): 1/8, ("y", "m"): 3/8}, source="data")
utility({"go": by("side", {"x": 1, "y": -4}), "hold": by("side", {"x": 0, "y": 0})}, source="elicited")
price({"k1": 1/20, "k2": 1/20}, source="elicited")
act("k1", once=True, kernel=point("lambda"), reads=["side"])
act("k2", once=True, kernel=point("lambda"), reads=["side"])
