# expect: TABLE_SHAPE
world("three states", closed=True)
horizon(2, source="elicited")
depth(2, source="elicited")
space({"side": ["x", "y"], "draw": ["p", "m"]})
prior({("x", "p"): 3/8, ("x", "m"): 1/8, ("y", "p"): 1/2}, source="data")
utility({"go": {("x", "p"): 1, ("x", "m"): 1, ("y", "p"): -4, ("y", "m"): -4}, "hold": by("side", {"x": 0, "y": 0})}, source="elicited")
price({"k1": 1/20, "k2": 1/20}, source="elicited")
act("k1", once=True, kernel=point("draw"), reads=["draw"])
act("k2", once=True, kernel=point("draw"), reads=["draw"])
