# A fitted fraction whose cell reads an elicited param: lawful (K16 admits it), the cell counts fitted (K17), the score is due.
# CHARTER v0.1 appendix A: the thought that changes nothing. decide+ at the root: think, test, paid 1/5.
world("p", closed=True)
horizon(2, source="elicited")
depth(1, source="elicited")
space({"health": ["sick", "well"]})
prior({"sick": 1/5, "well": 4/5}, source="data")
utility({"treat": {"sick": 0, "well": -2}, "leave": {"sick": -10, "well": 0}}, source="elicited")
price({"test": 1/2}, source="elicited")
act("test", once=False, kernel=table({"sick": {"+": 9/10, "-": 1/10}, "well": {"+": 1/5, "-": 4/5}}, source="data"), reads=["health"])
param("f0", 1/2, source="elicited")
depth_plus(2, source="elicited")
think(fraction=f0, source="fitted")
cost([100, 200], source="elicited")
rate(1/1000, source="elicited")
score(17/20, of="fraction", source="data")
