# A fitted cost table, fenced, with its held-out score; the fraction reads a fitted param so it says fitted too.
world("p", closed=True)
horizon(2, source="elicited")
depth(1, source="elicited")
space({"health": ["sick", "well"]})
prior({"sick": 1/5, "well": 4/5}, source="data")
utility({"treat": {"sick": 0, "well": -2}, "leave": {"sick": -10, "well": 0}}, source="elicited")
price({"test": 1/2}, source="elicited")
act("test", once=False, kernel=table({"sick": {"+": 9/10, "-": 1/10}, "well": {"+": 1/5, "-": 4/5}}, source="data"), reads=["health"])
param("f_hat", 1/2, source="fitted")
think(depth=2, fraction=f_hat, source="fitted")
cost([100, 200], source="fitted")
rate(1/1000, source="elicited")
score(17/20, source="data")
